from decouple import config

LOG_LEVEL = config("LOG_LEVEL", default="INFO")
TOKEN = config("TOKEN")
CLIENT_BATCH_SIZE = config("CLIENT_BATCH_SIZE", default=1000, cast=int)
INSERT_CHUNK_COUNT = config("INSERT_CHUNK_COUNT", default=20, cast=int)
SUMMARY_OUTPUT_TABLE = config("SUMMARY_OUTPUT_TABLE")
SUMMARY_HIST_OUTPUT_TABLE = config("SUMMARY_HIST_OUTPUT_TABLE")
DB_TICKERS_QUERY = config("DB_TICKERS_QUERY")
INSERTER_MAX_RETRIES = config("INSERTER_MAX_RETRIES", default=3, cast=int)
REQUEST_MAX_RETRIES = config("REQUEST_MAX_RETRIES", default=3, cast=int)
REQUEST_BACKOFF_FACTOR = config("REQUEST_BACKOFF_FACTOR", default=2, cast=int)
MSSQL_AD_LOGIN = config("MSSQL_AD_LOGIN", cast=bool, default=False)
MSSQL_SERVER = config("MSSQL_SERVER")
MSSQL_DATABASE = config("MSSQL_DATABASE")

if not MSSQL_AD_LOGIN:
    MSSQL_USERNAME = config("MSSQL_USERNAME")
    MSSQL_PASSWORD = config("MSSQL_PASSWORD")
